2024-08-06 20:35:55,831 INFO    StreamThr :2158982 [internal.py:wandb_internal():86] W&B internal server running at pid: 2158982, started at: 2024-08-06 20:35:55.831445
2024-08-06 20:35:55,832 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: status
2024-08-06 20:35:55,833 INFO    WriterThread:2158982 [datastore.py:open_for_write():85] open: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/run-eaj7x85o.wandb
2024-08-06 20:35:55,833 DEBUG   SenderThread:2158982 [sender.py:send():382] send: header
2024-08-06 20:35:55,833 DEBUG   SenderThread:2158982 [sender.py:send():382] send: run
2024-08-06 20:35:56,079 INFO    SenderThread:2158982 [dir_watcher.py:__init__():211] watching files in: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files
2024-08-06 20:35:56,080 INFO    SenderThread:2158982 [sender.py:_start_run_threads():1136] run started: eaj7x85o with start time 1722947755.831411
2024-08-06 20:35:56,096 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: check_version
2024-08-06 20:35:56,096 DEBUG   SenderThread:2158982 [sender.py:send_request():409] send_request: check_version
2024-08-06 20:35:56,228 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: run_start
2024-08-06 20:35:56,243 DEBUG   HandlerThread:2158982 [system_info.py:__init__():32] System info init
2024-08-06 20:35:56,244 DEBUG   HandlerThread:2158982 [system_info.py:__init__():47] System info init done
2024-08-06 20:35:56,244 INFO    HandlerThread:2158982 [system_monitor.py:start():194] Starting system monitor
2024-08-06 20:35:56,244 INFO    SystemMonitor:2158982 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-06 20:35:56,244 INFO    HandlerThread:2158982 [system_monitor.py:probe():214] Collecting system info
2024-08-06 20:35:56,245 INFO    SystemMonitor:2158982 [interfaces.py:start():190] Started cpu monitoring
2024-08-06 20:35:56,246 INFO    SystemMonitor:2158982 [interfaces.py:start():190] Started disk monitoring
2024-08-06 20:35:56,246 INFO    SystemMonitor:2158982 [interfaces.py:start():190] Started gpu monitoring
2024-08-06 20:35:56,247 INFO    SystemMonitor:2158982 [interfaces.py:start():190] Started memory monitoring
2024-08-06 20:35:56,248 INFO    SystemMonitor:2158982 [interfaces.py:start():190] Started network monitoring
2024-08-06 20:35:56,260 DEBUG   HandlerThread:2158982 [system_info.py:probe():196] Probing system
2024-08-06 20:35:56,261 DEBUG   HandlerThread:2158982 [system_info.py:_probe_git():181] Probing git
2024-08-06 20:35:56,263 DEBUG   HandlerThread:2158982 [system_info.py:_probe_git():189] Probing git done
2024-08-06 20:35:56,263 DEBUG   HandlerThread:2158982 [system_info.py:probe():244] Probing system done
2024-08-06 20:35:56,263 DEBUG   HandlerThread:2158982 [system_monitor.py:probe():223] {'os': 'Linux-6.5.0-41-generic-x86_64-with-glibc2.35', 'python': '3.10.13', 'heartbeatAt': '2024-08-06T12:35:56.260443', 'startedAt': '2024-08-06T12:35:55.826863', 'docker': None, 'cuda': None, 'args': ('--local_rank=0', '--deepspeed', 'configs/ds_config_zero2_no_offload.json', '--model_name_or_path', '/home/rwkv/JL/model/qwen2-1.5b', '--data_path', '/home/rwkv/JL/model/MetaMathQA', '--dataset_field', 'query', 'response', '--dataset_split', 'train[:395000]', '--output_dir', '/home/rwkv/JL/out_model/Gemma-meta-2btest', '--num_train_epochs', '1', '--model_max_length', '512', '--per_device_train_batch_size', '2', '--gradient_accumulation_steps', '16', '--save_strategy', 'steps', '--save_steps', '1000', '--save_total_limit', '2', '--learning_rate', '2e-5', '--weight_decay', '0.', '--warmup_ratio', '0.03', '--logging_steps', '1', '--lr_scheduler_type', 'cosine', '--report_to', 'wandb', '--merge', 'True'), 'state': 'running', 'program': '/home/rwkv/JL/GMM/llama/gmm.py', 'codePathLocal': 'gmm.py', 'codePath': 'llama/gmm.py', 'git': {'remote': 'https://github.com/JL-er/GMM.git', 'commit': None}, 'email': '997529190@qq.com', 'root': '/home/rwkv/JL/GMM', 'host': 'rwkv-Z790M-AORUS-ELITE-AX', 'username': 'rwkv', 'executable': '/home/rwkv/miniconda3/bin/python', 'cpu_count': 20, 'cpu_count_logical': 28, 'cpu_freq': {'current': 1231.5181071428572, 'min': 800.0, 'max': 5000.0}, 'cpu_freq_per_core': [{'current': 1337.859, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1319.48, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 1473.02, 'min': 800.0, 'max': 5500.0}, {'current': 1346.497, 'min': 800.0, 'max': 5500.0}, {'current': 1247.397, 'min': 800.0, 'max': 5500.0}, {'current': 2520.493, 'min': 800.0, 'max': 5500.0}, {'current': 1495.643, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 800.0, 'min': 800.0, 'max': 5600.0}, {'current': 1330.285, 'min': 800.0, 'max': 5600.0}, {'current': 1204.307, 'min': 800.0, 'max': 5500.0}, {'current': 1357.911, 'min': 800.0, 'max': 5500.0}, {'current': 1141.044, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 5500.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 1400.822, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}, {'current': 800.0, 'min': 800.0, 'max': 4300.0}], 'disk': {'/': {'total': 916.2753829956055, 'used': 443.3817253112793}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 62.5532341003418}}
2024-08-06 20:35:56,263 INFO    HandlerThread:2158982 [system_monitor.py:probe():224] Finished collecting system info
2024-08-06 20:35:56,264 INFO    HandlerThread:2158982 [system_monitor.py:probe():227] Publishing system info
2024-08-06 20:35:56,264 DEBUG   HandlerThread:2158982 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-08-06 20:35:56,264 DEBUG   HandlerThread:2158982 [system_info.py:_save_pip():68] Saving pip packages done
2024-08-06 20:35:56,264 DEBUG   HandlerThread:2158982 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-08-06 20:35:57,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/conda-environment.yaml
2024-08-06 20:35:57,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/requirements.txt
2024-08-06 20:35:57,952 DEBUG   HandlerThread:2158982 [system_info.py:_save_conda():87] Saving conda packages done
2024-08-06 20:35:57,953 DEBUG   HandlerThread:2158982 [system_info.py:_save_code():90] Saving code
2024-08-06 20:35:57,954 DEBUG   HandlerThread:2158982 [system_info.py:_save_code():111] Saving code done
2024-08-06 20:35:57,954 DEBUG   HandlerThread:2158982 [system_info.py:_save_patches():128] Saving git patches
2024-08-06 20:35:57,957 ERROR   HandlerThread:2158982 [system_info.py:_save_patches():169] Error generating diff: Reference at 'refs/remotes/origin/main' does not exist
2024-08-06 20:35:57,957 DEBUG   HandlerThread:2158982 [system_info.py:_save_patches():170] Saving git patches done
2024-08-06 20:35:57,957 INFO    HandlerThread:2158982 [system_monitor.py:probe():229] Finished publishing system info
2024-08-06 20:35:57,958 DEBUG   SenderThread:2158982 [sender.py:send():382] send: files
2024-08-06 20:35:57,958 INFO    SenderThread:2158982 [sender.py:_save_file():1392] saving file wandb-metadata.json with policy now
2024-08-06 20:35:57,958 INFO    SenderThread:2158982 [sender.py:_save_file():1392] saving file code/llama/gmm.py with policy now
2024-08-06 20:35:57,960 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: stop_status
2024-08-06 20:35:57,960 DEBUG   SenderThread:2158982 [sender.py:send_request():409] send_request: stop_status
2024-08-06 20:35:57,962 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: internal_messages
2024-08-06 20:35:58,079 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/conda-environment.yaml
2024-08-06 20:35:58,079 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/code/llama/gmm.py
2024-08-06 20:35:58,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/wandb-metadata.json
2024-08-06 20:35:58,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/code
2024-08-06 20:35:58,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/code/llama
2024-08-06 20:35:58,339 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6
2024-08-06 20:35:58,339 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5187', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:58,339 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/eaj7x85o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923DB8C5161D8</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:58,811 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa
2024-08-06 20:35:58,811 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:35:58,811 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/eaj7x85o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923DBA431C965</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:35:59,219 DEBUG   SenderThread:2158982 [sender.py:send():382] send: telemetry
2024-08-06 20:35:59,219 DEBUG   SenderThread:2158982 [sender.py:send():382] send: config
2024-08-06 20:35:59,220 DEBUG   SenderThread:2158982 [sender.py:send():382] send: metric
2024-08-06 20:35:59,220 DEBUG   SenderThread:2158982 [sender.py:send():382] send: telemetry
2024-08-06 20:35:59,220 DEBUG   SenderThread:2158982 [sender.py:send():382] send: metric
2024-08-06 20:35:59,220 WARNING SenderThread:2158982 [sender.py:send_metric():1343] Seen metric with glob (shouldn't happen)
2024-08-06 20:35:59,220 DEBUG   SenderThread:2158982 [sender.py:send():382] send: telemetry
2024-08-06 20:35:59,220 DEBUG   SenderThread:2158982 [sender.py:send():382] send: telemetry
2024-08-06 20:35:59,220 DEBUG   SenderThread:2158982 [sender.py:send():382] send: config
2024-08-06 20:36:00,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/output.log
2024-08-06 20:36:00,110 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:36:00,111 DEBUG   SenderThread:2158982 [sender.py:send():382] send: metric
2024-08-06 20:36:00,111 DEBUG   SenderThread:2158982 [sender.py:send():382] send: metric
2024-08-06 20:36:00,111 DEBUG   SenderThread:2158982 [sender.py:send():382] send: metric
2024-08-06 20:36:00,111 DEBUG   SenderThread:2158982 [sender.py:send():382] send: metric
2024-08-06 20:36:00,111 DEBUG   SenderThread:2158982 [sender.py:send():382] send: history
2024-08-06 20:36:00,111 DEBUG   SenderThread:2158982 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:36:00,111 INFO    SenderThread:2158982 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:36:00,171 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa
2024-08-06 20:36:00,171 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:36:00,171 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/eaj7x85o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923DBF6B80CE1</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:36:00,171 INFO    wandb-upload_1:2158982 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 20:36:00,244 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6
2024-08-06 20:36:00,244 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5187', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:36:00,244 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/eaj7x85o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923DBD73AB1A0</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:36:00,244 INFO    wandb-upload_0:2158982 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2785, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 2759, in upload_file
    response.raise_for_status()
  File "/home/rwkv/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
wandb.sdk.lib.retry.TransientError: None
2024-08-06 20:36:01,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_created():271] file/dir created: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/wandb-summary.json
2024-08-06 20:36:01,112 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: status_report
2024-08-06 20:36:01,905 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:36:01,906 DEBUG   SenderThread:2158982 [sender.py:send():382] send: history
2024-08-06 20:36:01,906 DEBUG   SenderThread:2158982 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:36:01,906 INFO    SenderThread:2158982 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:36:02,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/wandb-summary.json
2024-08-06 20:36:02,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/output.log
2024-08-06 20:36:02,384 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=cbd48e6c4e0d47f9f2709d698e4a5b9e1e734128a0519067d6951636812935c6
2024-08-06 20:36:02,384 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5187', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:36:02,384 ERROR   wandb-upload_0:2158982 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/eaj7x85o/wandb-metadata.json</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/eaj7x85o/wandb-metadata.json</Resource><Region>wandb-local</Region><RequestId>17E923DC7D802957</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:36:02,393 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2761] upload_file exception http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa: 503 Server Error: Service Unavailable for url: http://dian.sea-group.org:9098/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=FS%2BimP8205gHBuibMeAr0A%3D%3D%2F20240806%2Fwandb-local%2Fs3%2Faws4_request&X-Amz-Date=20240806T123558Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-User=mobius&X-Amz-Signature=1cc11819b50b57ef5768fcdf0bd4e4645cc91699dff73b57b746d4acd5b523fa
2024-08-06 20:36:02,393 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2763] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br, zstd', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '14100', 'Authorization': 'Basic dXNlcjpsb2NhbC0yNWIwMmYyNWUzNGUzOTlkYmI1OWJjNjFlZWVmY2RkZTYzNDRhOGI2'}
2024-08-06 20:36:02,393 ERROR   wandb-upload_1:2158982 [internal_api.py:upload_file():2765] upload_file response body: b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SlowDown</Code><Message>Resource requested is unreadable, please reduce your request rate</Message><Key>mobius/huggingface/eaj7x85o/code/llama/gmm.py</Key><BucketName>local-files</BucketName><Resource>/local-files/mobius/huggingface/eaj7x85o/code/llama/gmm.py</Resource><Region>wandb-local</Region><RequestId>17E923DC7CE69AA7</RequestId><HostId>18bf63b7-01d2-4a3f-8eda-6b508ac9c4f3</HostId></Error>'
2024-08-06 20:36:03,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/output.log
2024-08-06 20:36:03,573 DEBUG   HandlerThread:2158982 [handler.py:handle_request():146] handle_request: partial_history
2024-08-06 20:36:03,574 DEBUG   SenderThread:2158982 [sender.py:send():382] send: history
2024-08-06 20:36:03,574 DEBUG   SenderThread:2158982 [sender.py:send_request():409] send_request: summary_record
2024-08-06 20:36:03,575 INFO    SenderThread:2158982 [sender.py:_save_file():1392] saving file wandb-summary.json with policy end
2024-08-06 20:36:04,080 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/wandb-summary.json
2024-08-06 20:36:04,081 INFO    Thread-12 :2158982 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/rwkv/JL/GMM/llama/wandb/run-20240806_203555-eaj7x85o/files/output.log
